### ISSUE TITLE
[Feature request] Display shortcuts

### ISSUE THREAD

**Issue by joaopauloalbq** [ArturGaspar/krunner-appmenu#1]
É possível passar mais informações para o Krunner? Exibir o atalho do comando também seria muito útil.

![Screenshot_20200517_171258](https://user-images.githubusercontent.com/9905202/82159386-197d1200-9864-11ea-932a-a87d0ee0ee78.png)

**Comment by ArturGaspar** [comment]
Done.

**Comment by joaopauloalbq** [comment]
Awesome, thanks!
