### ISSUE TITLE
[Feature request] Open Krunner with only appmenu plugin by pressing the Alt key.

### ISSUE THREAD

**Issue by joaopauloalbq** [ArturGaspar/krunner-appmenu#3]
Link that may be useful:
https://www.reddit.com/r/kde/comments/ayqhnq/tip_you_can_trigger_a_specific_krunner_plugin/
https://wiki.archlinux.org/index.php/KRunner#Open_KRunner_with_the_Meta_key

**Comment by ArturGaspar** [comment]
Thank you! I was just wondering if there was a way to do that!

**Comment by joaopauloalbq** [comment]
Didn't work for me :(

**Comment by ArturGaspar** [comment]
Doesn't work for me either, although KRunner initially does display "Search Application menu".

**Comment by alex1701c** [comment]
This is a bug that already got fixed on the KDE site of things, please see https://invent.kde.org/plasma/milou/-/merge_requests/7

**Comment by Kishore96in** [comment]
Using `kwriteconfig5 --file kwinrc --group ModifierOnlyShortcuts --key Alt "org.kde.krunner,/App,,displaySingleRunner,appmenurunner"`, it works now in Plasma 5.19.90.

**Comment by ArturGaspar** [comment]
Use `kwriteconfig5 --file kwinrc --group ModifierOnlyShortcuts --key Alt org.kde.krunner,/App,,displaySingleRunner,krunner_appmenu`

(I changed the plugin name from appmenurunner.)

**Comment by Kishore96in** [comment]
> Use `kwriteconfig5 --file kwinrc --group ModifierOnlyShortcuts --key Alt org.kde.krunner,/App,,displaySingleRunner,krunner_appmenu`
> 
> (I changed the plugin name from appmenurunner.)

Would you consider adding this to the README? Most people might not know how to enable this feature.

**Comment by ArturGaspar** [comment]
@Kishore96in Done.
