### ISSUE TITLE
Upcoming KDE Store

### ISSUE THREAD

**Issue by alex1701c** [ArturGaspar/krunner-appmenu#7]
Hello,
So far there has not been a standardized place from where to install Krunner plugins, but in the next Plasma release,  Krunner will be integrated with the KDE Store. This will make it far more easier to discover and install Krunner plugins.
To make sure your plugin is included and available as soon as this is released, add an install and uninstall script to your plugin, and upload your work to the KDE store (https://store.kde.org/browse/cat/628/order/latest/).

If you have any questions, or if you need help, don't hesitate to ask!

Thank you!

**Comment by ArturGaspar** [comment]
https://store.kde.org/p/1487175/

Feel free to reopen if you have issues installing it.
